// events about topic
export const TOPIC_SELECTED = 'TOPIC_SELECTED';
export const TOPIC_DESELECTED = 'TOPIC_DESELECTED';

export const PUSH_UNDO_STACK = 'PUSH_UNDO_STACK';
export const UNDO_OR_REDO_TRIGGERED = 'UNDO_OR_REDO_TRIGGERED';