// constants for sheet
export const UPDATE_SHEET_BGCOLOR = 'UPDATE_SHEET_BGCOLOR';
export const UPDATE_SHEET_INFO_ITEM_MODE = 'UPDATE_SHEET_INFO_ITEM_MODE';

// constants for topic
export const UPDATE_TOPIC_TITLE = 'UPDATE_TOPIC_TITLE';

export const UPDATE_TOPIC_FONTSIZE = 'UPDATE_TOPIC_FONTSIZE';
export const UPDATE_TOPIC_FONTCOLOR = 'UPDATE_TOPIC_FONTCOLOR';
export const UPDATE_TOPIC_ISFONTBOLD = 'UPDATE_TOPIC_ISFONTBOLD';
export const UPDATE_TOPIC_ISFONTITALIC = 'UPDATE_TOPIC_ISFONTITALIC ';
export const UPDATE_TOPIC_ISFONTLINETHROUGH = 'UPDATE_TOPIC_ISFONTLINETHROUGH';

export const UPDATE_TOPIC_SHAPECLASS = 'UPDATE_TOPIC_SHAPECLASS';
export const UPDATE_TOPIC_FILLCOLOR = 'UPDATE_TOPIC_FILLCOLOR';
export const UPDATE_TOPIC_STROKEWIDTH = 'UPDATE_TOPIC_BORDERWIDTH';
export const UPDATE_TOPIC_STROKECOLOR = 'UPDATE_TOPIC_STROKECOLOR';

export const UPDATE_TOPIC_LINECLASS = 'UPDATE_TOPIC_LINECLASS';
export const UPDATE_TOPIC_LINEWIDTH = 'UPDATE_TOPIC_LINEWIDTH';
export const UPDATE_TOPIC_LINECOLOR = 'UPDATE_TOPIC_LINECOLOR';

export const UPDATE_TOPIC_LABEL = 'UPDATE_TOPIC_LABEL';

export const ADD_CHILD_TOPIC = 'ADD_CHILD_TOPIC';
export const Add_PARENT_TOPIC = 'Add_PARENT_TOPIC';
export const REM_SELF_TOPIC = 'REM_SELF_TOPIC';